### ISSUE TITLE
マッチングできた生徒の名前、クラス、ID、パスワードなどを個別にプリントアウトできるようなファイルを作る

### ISSUE THREAD

**Issue by sota0121** [sota0121/jiyugaoka-st-dongri-automation#4]
## ToDo

- [x] toolbox.py の移動
- [ ] マッチングに成功した生徒ごとのDoc（形式問わず）を作る
  - [ ] ファイルは分けず、一つのHTMLファイルに出力する。Page BreakするようにCSSまたはHTMLを加工する。
- [ ] 上記DocをPDFファイルとして生徒ごとに出力する。生徒ごとにページを分ける。ファイルは一緒にしておく。
- [x] ~~出力した生徒の一覧を作る。~~ これはエクセルですでにあるのでいらない。

---

pandas, Pdfkit を使うとなんとかできそう。

- https://pypi.org/project/pdfkit/
- https://stackoverflow.com/questions/33155776/export-pandas-dataframe-into-a-pdf-file-using-python

**Comment by sota0121** [comment]
複数ページに分ける手段を模索した。複数のHTMLを入力に設定すれば、できると思ったが、 `wkhtmltopdf` 側で不明のエラーが発生してしまい、詰まった。

したがって、もとのHTMLファイルを適切に作り、PDF出力は素直に行うスタイルが良さそう。


https://stackoverflow.com/questions/45422378/is-there-a-quick-way-to-turn-a-pandas-dataframe-into-a-pretty-html-table


このへんをみるに、pandas が出力したHTMLファイルは戻り地で文字列として取得できる。これをいろいろと加工したり、予め適用するCSSを用意したりすることで、HTMLファイルを（果ては、PDFファイルを）調整することができそう。
